= Android Bootcamp Training

26 May 2014

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/bootcamp-2014-05-26.git

or

   download a Zip archive by clicking the link at the top of the page or using the link:
  
	https://github.com/mailat/bootcamp-2014-05-26/zipball/master

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

== Homework Day 01

- Add in Android manifest XML the permission to use the Internet
- Read about AsyncTask maybe move the logic from postTwitterUpdate into one

== Homework Day 02

- If the user has no credentials, display a Toast mesaage and redirect the user to the PefsActivty
- Add in the "activity_status.xml" a background image for the activity background ( use this image http://ts4.mm.bing.net/th?id=HN.608004293658150413&pid=1.7 or other PNG background )
- Style be button in the "activity_status.xml" to have round corners (use no image, just a layout)

== Homework Day 03

- detect the receiving of an SMS with an BroadcastReceiver and log the content in this SMS

== Homework Day 04

- Complete the forecast as a ListActivity, take the values from the API call http://api.openweathermap.org/data/2.5/weather?q=Shanghai,en&units=metric

== Homework Day 05

- Bring the sample WeatherApp more into direction of the http://coolmaterial.com/wp-content/uploads/2013/05/yahoo-weather-app.jpg and the flat icons from http://fc04.deviantart.net/fs10/f/2006/108/2/c/Flat_Weather_Icons.zip